sudo: required
services:
  - docker

before_install:
  - docker build -t vinniiee/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vinniiee/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-169022016886"
  bucket_path: "docker-react"
  on:
    branch: master
    access_key_id: $AWS_BEANSTALK_ACCESS_KEY_ID
    secret_access_key:
      secure: "$AWS_BEANSTALK_SECRET_ACCESS_KEY"
